// Original cases. The Cartesian product checks layout/scope invariance against
// the reference engine, including multiple findings on one source line.
const seeds = [
  ['valid-v-html', '<div v-html/>'],
  ['valid-v-html', '<div v-html=""/>'],
  ['valid-v-html', '<div v-html=" "/>'],
  ['valid-v-html', '<div v-html="/* comment */ value"/>'],
  ['valid-v-html', '<div v-html:[field].a.b="value"/>'],
  ['valid-v-text', '<div v-text/>'],
  ['valid-v-text', '<div v-text=""/>'],
  ['valid-v-text', '<div v-text=" "/>'],
  ['valid-v-text', '<div v-text="/* comment */ value"/>'],
  ['valid-v-text', '<div v-text:[field].a.b="value"/>'],
  ['valid-v-show', '<div v-show/>'],
  ['valid-v-show', '<div v-show=""/>'],
  ['valid-v-show', '<div v-show=" "/>'],
  ['valid-v-show', '<div v-show="/* comment */ value"/>'],
  ['valid-v-show', '<div v-show:[field].a.b="value"/>'],
  ['valid-v-once', '<div v-once/>'],
  ['valid-v-once', '<div v-once=""/>'],
  ['valid-v-once', '<div v-once=" "/>'],
  ['valid-v-once', '<div v-once="/* comment */ value"/>'],
  ['valid-v-once', '<div v-once:[field].a.b="value"/>'],
  ['valid-v-cloak', '<div v-cloak/>'],
  ['valid-v-cloak', '<div v-cloak=""/>'],
  ['valid-v-cloak', '<div v-cloak=" "/>'],
  ['valid-v-cloak', '<div v-cloak="/* comment */ value"/>'],
  ['valid-v-cloak', '<div v-cloak:[field].a.b="value"/>'],
  ['valid-v-if', '<div v-if/>'],
  ['valid-v-if', '<div v-if=""/>'],
  ['valid-v-if', '<div v-if:[field].a.b="value"/>'],
  ['valid-v-if', '<div v-if="value" v-else/>'],
  ['valid-v-else-if', '<i v-if="first"/><div v-else-if/>'],
  ['valid-v-else-if', '<i v-if="first"/><div v-else-if=""/>'],
  ['valid-v-else-if', '<i v-if="first"/><div v-else-if:[field].a.b="value"/>'],
  ['valid-v-else-if', '<div v-else-if="value"/>'],
  ['valid-v-else', '<i v-if="first"/><div v-else="value"/>'],
  ['valid-v-else', '<i v-if="first"/><div v-else:[field].a.b/>'],
  ['valid-v-else', '<div v-else/>'],
  ['valid-v-memo', '<div v-memo/>'],
  ['valid-v-memo', '<div v-memo:[field].a.b="value"/>'],
  ['valid-v-memo', '<div v-memo="a ? { bad: true } : value + 1"/>'],
  ['valid-v-memo', '<div v-for="item in items"><span v-memo="[item]"/></div>'],
  ['valid-v-is', '<div v-is/>'],
  ['valid-v-is', '<div v-is:[field].a.b="value"/>'],
  ['valid-v-is', '<Component v-is="value"/>'],
  ['no-deprecated-v-on-native-modifier', '<Component @click.foo.native.bar="handler"/>'],
  ['use-v-on-exact', '<button @click="go" @click.ctrl="go"/>'],
  ['use-v-on-exact', '<input @keydown.prevent="go" @keydown.ctrl="go"/>'],
  ['use-v-on-exact', '<Component @click.native="go" @click.native.meta="go"/>'],
  ['use-v-on-exact', '<button @[event]="go" @[event].ctrl="go"/>'],
  ['require-v-for-key', '<li v-for="item in items"/>'],
  ['require-v-for-key', '<li v-for="item in items" :key="item.id"/>'],
  ['no-v-for-template-key-on-child', '<template v-for="item in items"><p :key="item.id"/></template>'],
  ['no-v-for-template-key-on-child', '<template v-for="item in items" :key="item.id"><p :key="item.id"/></template>'],
  ['valid-v-for', '<Comp v-for="item in items" :key="constant"/>'],
  ['valid-v-for', '<Comp v-for="item in items" :key="item.id"/>'],
  ['valid-v-model', '<input v-model:bad.custom="a + b"/>'],
  ['valid-v-model', '<Comp v-model:title.custom="state.title"/>'],
  ['no-v-html', '<p v-html="html"/>'],
  ['no-use-v-if-with-v-for', '<p v-for="item in items" v-if="item.visible"/>'],
  ['no-template-key', '<template :key="id"><i/></template>'],
  ['no-useless-mustaches', '<p>{{ `hello` }} {{ "world" }}</p>'],
  ['no-useless-mustaches', '<p>{{ `hello ${name}` }}</p>'],
  ['no-duplicate-attributes', '<p class="a" :class="b"/>'],
  ['no-duplicate-attributes', '<p :[key]="a" :key="b"/>'],
  ['require-component-is', '<component/>'],
  ['require-component-is', '<component :is="current"/>'],
  ['no-v-text-v-html-on-component', '<Comp v-html="html"/>'],
  ['no-v-text-v-html-on-component', '<g v-text="content"/>'],
  ['no-v-text-v-html-on-component', '<g v-text="content"/>', [{ ignoreElementNamespaces: true }]],
  ['no-v-text-v-html-on-component', '<svg><g v-text="content"/></svg>'],
  ['no-v-text-v-html-on-component', '<math><mi v-text="content"/></math>'],
  ['no-useless-v-bind', '<input :title="`hello`"/>'],
  ['no-useless-v-bind', '<input :title.prop="`hello`"/>'],
  ['this-in-template', '<p>{{ this.first }} {{ this.second }}</p>'],
  ['this-in-template', '<p :title="`Hello ${this.name}`"/>'],
  ['this-in-template', '<p :title="&quot;😀&quot; + this.name"/>'],
  ['no-static-inline-styles', '<p :style="{color: tone, display: \'flex\'}"/>'],
  ['no-dupe-v-else-if', '<p v-if="a || b"/><!-- chain --><p v-else-if="a &amp;&amp; b"/>'],
  ['no-dupe-v-else-if', '<p v-if="a"/><span/><p v-else-if="a"/>'],
  ['no-textarea-mustache', '<textarea>{{ first }} {{ second }}</textarea>'],
  ['no-child-content', '<p title=">" v-html="html"> overwritten </p>'],
  ['no-child-content', '<p v-text="text"><!-- comment --></p>'],
]

export const generatedCases = seeds.flatMap(([name, template, options = []], index) =>
  ['\n', '\r\n'].flatMap((newline, layout) => [
    template,
    `<section data-label="😀 тест">\n  ${template}\n</section>`,
    `<section v-for="row in rows" :key="row.id">\n${template}\n</section>`,
    `<Panel #default="{ value }">\n${template}\n</Panel>`,
  ].map((body, scope) => ({
    id: `generated/${name}/${index}/${layout}/${scope}`,
    rule: `vue/${name}`, options,
    code: `<template>\n${body}\n</template>\n<script setup>\nconst sentinel = '😀'\n</script>\n`.replaceAll('\n', newline),
  }))),
)
