const setup = (script, template = '<i/>') => `<script setup lang="ts">\n${script}\n</script>\n<template>${template}</template>`
const options = body => `<script>export default { props: ['value', 'items'], ${body} }</script>`
const seeds = [
  ['setup script only', '<script setup>const props=defineProps({value:Number}); props.value++</script>', 1],
  ['shadowed callback', setup('const props=defineProps({value:Number}); function f(props) { props.value++ }; props.value++'), 1],
  ['shadowed block', setup('const props=defineProps({value:Number}); { const props={value:0}; props.value++ }; props.value++'), 1],
  ['shadowed loop', setup('const props=defineProps({value:Number}); for (const props of rows) { props.value++ }; props.value++'), 1],
  ['shadowed catch', setup('const props=defineProps({value:Number}); try {} catch(props) { props.value++ }; props.value++'), 1],
  ['closed over binding', setup('const props=defineProps({value:Number}); function f() { props.value++ }; const g=()=>props.value++'), 2],
  ['shadowed alias', setup('const {value}=defineProps({value:Object}); function f(value) { value.n++ }; value.n++'), 1],
  ['destructured local reassignment', setup('const {value}=defineProps({value:Number}); value++'), 0],
  ['script and template', setup('const props=defineProps({value:Number}); props.value++', '<button @click="props.value++; props.value++"/>'), 3],
  ['optional mutation', setup('const props=defineProps({items:Array}); props.items?.push?.(1)'), 1],
  ['copy is independent', setup('const props=defineProps({items:Array}); props.items.slice().push(1)'), 0],
  ['Object.assign target', setup('const props=defineProps({value:Object}); Object.assign(props.value, {a:1})'), 1],
  ['Object.assign copy', setup('const props=defineProps({value:Object}); Object.assign({}, props.value)'), 0],
  ['shadowed Object', setup('const props=defineProps({value:Object}); function f(Object) { Object.assign(props.value, {a:1}) }'), 1, [], 'Object is a local parameter, not the built-in Object.assign'],
  ['template optional mutation', setup('const props=defineProps({items:Array})', '<button @click="props.items?.push?.(1)"/>'), 1],
  ['template callback shadow', setup('const props=defineProps({items:Array})', '<button @click="items.map(props => props.items.push(1))"/>'), 0],
  ['template literal location', setup('const props=defineProps({value:Number})', '<button @click="log(&quot;😀&quot;); props.value++"/>'), 1],
  ['constant props alias', setup('const props=defineProps({value:Object}); const alias=props; alias.value.n++'), 0],
  ['constant prop value alias', setup('const props=defineProps({value:Object}); const alias=props.value; alias.n++'), 0],
  ['constant instance alias', options('methods: { update() { const vm=this; vm.value++ } }'), 1],
  ['named component', '<script>const component=defineComponent({props:["value"], methods:{update(){this.value++}}}); export default component</script>', 1],
  ['uninitialized export', '<script>let component; export default component</script>', 0],
  ['unrelated wrapper', '<script>export default wrap({props:["value"], methods:{update(){this.value++}}})</script>', 0],
  ['options this', options('methods: { update() { this.value++; this.items.push(1) } }'), 2],
  ['options arrow closure', options('methods: { update() { const f=()=>this.value++; f() } }'), 1],
  ['options ordinary closure', options('methods: { update() { function f() { this.value++ }; f() } }'), 1, [], 'An ordinary nested function does not inherit the component this'],
  ['options setup shadow', options('setup(props) { function f(props) { props.value++ }; props.value++ }'), 1],
  ['options setup destructuring', options('setup({value: local}) { local.n++; local=1 }'), 1],
  ['unrelated method parameter', options('methods: { update(props) { props.value++ } }'), 0],
  ['ordinary script macro', '<script>const props=defineProps({value:Number}); props.value++</script>', 0],
  ['both script blocks', '<script>const props=defineProps({value:Number})</script><script setup>props.value++</script>', 0],
  ['setup binding shadows options prop', '<script>export default {props:["value"]}</script>'+setup('const value={n:0}', '<button @click="value.n++"/>'), 1, [], 'A script setup binding shadows an Options API prop in the template'],
  ['shallow direct script write', setup('const props=defineProps({value:Object}); props.value={n:1}; props.value.n++'), 1, [{shallowOnly:true}]],
  ['shallow destructured reference', setup('const {value}=defineProps({value:Object}); value.n++'), 0, [{shallowOnly:true}]],
  ['template instance ignores loop shadow', '<script>export default {props:["value"]}</script><template><div v-for="value in values"><button @click="this.value++"/></div></template>', 1],
]
export const propCases = seeds.flatMap(([name, code, expectedCount, ruleOptions = [], intentionalDifference]) => [false, true].map(crlf => ({
  id: `props/${name}/${crlf ? 'crlf' : 'lf'}`,
  rule: 'vue/no-mutating-props', options: ruleOptions, expectedCount,
  ...(intentionalDifference ? { intentionalDifference, expectedOwnCount: 0 } : {}),
  code: (`<!-- 😀 scope regression -->\n` + code).replaceAll('\n', crlf ? '\r\n' : '\n'),
  languageOptions: { ecmaVersion: 'latest', parserOptions: { parser: '@typescript-eslint/parser' } },
})))
