import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'
import assert from 'node:assert/strict'
import vue from 'eslint-plugin-vue'
import { structuralRuleNames } from '../dist/structural.js'

const require = createRequire(import.meta.url)
const enginePackage = require.resolve('oxlint/package.json')
const engine = JSON.parse(fs.readFileSync(enginePackage, 'utf8'))
const native = JSON.parse(execFileSync(process.execPath, [path.join(path.dirname(enginePackage), engine.bin.oxlint), '--rules', '--format=json'], { encoding: 'utf8' })).filter(rule => rule.scope === 'vue')
const corpus = JSON.parse(fs.readFileSync(new URL('../test/compat/upstream.json', import.meta.url), 'utf8'))
const baseline = JSON.parse(fs.readFileSync(new URL('../test/compat/baseline.json', import.meta.url), 'utf8'))
assert.equal(vue.meta.version, corpus.version)
const rules = Object.entries(vue.rules).map(([name, rule]) => {
  const own = structuralRuleNames.includes(`vue/${name}`)
  const nativeRule = native.find(item => item.value === name)
  const categories = rule.meta.docs.categories ?? []
  const upstreamCases = corpus.cases.filter(entry => entry.rule === `vue/${name}`).length
  const knownDifferences = Object.keys(baseline).filter(id => id.startsWith(`${name}/`)).length
  const notes = []
  let status = 'missing'
  if (own) {
    status = 'implemented'
    if (rule.meta.fixable || rule.meta.hasSuggestions) notes.push('Template autofixes/suggestions not implemented')
    if (knownDifferences) notes.push(`${knownDifferences} reviewed upstream case difference`)
    if (name === 'no-template-key') notes.push('Vue 3 conditional template keys intentionally allowed')
    if (name === 'no-mutating-props') notes.push('Six additional scope cases intentionally avoid reference false positives')
    if (notes.length) status = 'partial'
  } else if (nativeRule) {
    status = 'native'
    notes.push('Available in oxlint; options and broader wrapper behavior remain unmeasured')
  } else if (name === 'no-parsing-error') {
    status = 'partial'
    notes.push('Compiler parsing diagnostics only; reference options and severity not implemented')
  }
  const priority = categories.includes('vue3-essential') ? 'P0' : categories.includes('vue3-strongly-recommended') ? 'P1' : categories.includes('vue3-recommended') ? 'P2' : 'P3'
  return { name, status, priority, categories, deprecated: Boolean(rule.meta.deprecated), upstreamCases, knownDifferences, upstreamFixable: Boolean(rule.meta.fixable), upstreamSuggestions: Boolean(rule.meta.hasSuggestions), nativeFix: nativeRule?.fix ?? null, url: rule.meta.docs.url, notes }
}).toSorted((a, b) => a.priority.localeCompare(b.priority) || a.name.localeCompare(b.name))
const counts = Object.fromEntries(['implemented', 'native', 'partial', 'missing'].map(status => [status, rules.filter(rule => rule.status === status).length]))
const report = { referenceVersion: vue.meta.version, oxlintVersion: engine.version, counts, projectSpecificRules: structuralRuleNames.filter(name => !vue.rules[name.slice(4)]), rules }
const markdown = `# Full Vue rule inventory\n\nGenerated by \`pnpm rules:matrix\` from eslint-plugin-vue ${vue.meta.version}, oxlint ${engine.version}, built local rules and the committed upstream corpus.\n\n${rules.length} reference rules: ${Object.entries(counts).map(([key, value]) => `**${value} ${key}**`).join(', ')}.\n\n- **implemented**: local diagnostic implementation with imported upstream cases; this is not exhaustive behavioral proof.\n- **partial**: local implementation with known behavior differences or missing reference fixes/suggestions.\n- **native**: present in oxlint; config and CLI severity are honored for the selected native SFC pass, while broader wrapper parity remains unmeasured. Native fixes apply only inside scripts.\n- **missing**: no implementation under this reference name.\n- **P0/P1/P2**: Vue 3 Essential / Strongly Recommended / Recommended; **P3**: other, including Vue 2-only and uncategorized rules. Deprecated rules remain visible.\n\nCase counts measure diagnostic count, severity and start location, not wording, end ranges, fixes or suggestions. See [behavioral coverage](compatibility.md). Priority is for implementation backlog, not default severity.\n\nProject-specific rules: ${report.projectSpecificRules.map(name => `\`${name}\``).join(', ')}.\n\n| Rule | Priority | Status | Upstream cases | Notes |\n|---|---|---|---:|---|\n` + rules.map(rule => `| [${rule.name}](${rule.url}) | ${rule.priority} | ${rule.status} | ${rule.upstreamCases || '—'} | ${[...(rule.deprecated ? ['Deprecated upstream'] : []), ...rule.notes].join('; ')} |`).join('\n') + '\n'
for (const [name, content] of [['rules-matrix.json', JSON.stringify(report, null, 2) + '\n'], ['rules-matrix.md', markdown]]) {
  const destination = new URL(`../docs/${name}`, import.meta.url)
  if (process.argv.includes('--check')) assert.equal(fs.readFileSync(destination, 'utf8'), content, `${name} is stale; run pnpm rules:matrix`)
  else fs.writeFileSync(destination, content)
}
console.log(`${rules.length} reference rules: ${JSON.stringify(counts)}`)
