/**
 * Static port of @antfu/eslint-config 9.5.1 to oxlint and oxfmt.
 *
 * Oxlint receives every compatible JavaScript, TypeScript, import, Node,
 * JSDoc, Unicorn, RegExp, test and Vue rule. Rules that require ESLint-only
 * plugins, custom parsers or type information are omitted. Oxfmt covers the
 * stylistic/perfectionist half across JS, TS, Vue, JSON/JSONC/JSON5, YAML,
 * TOML, Markdown, HTML and CSS.
 */
export const lintConfig = {
  plugins: ['typescript', 'unicorn', 'import', 'node', 'jsdoc', 'vitest', 'vue'],
  env: {
    browser: true,
    node: true,
    es2024: true,
  },
  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    defineModel: 'readonly',
    defineOptions: 'readonly',
    defineSlots: 'readonly',
    withDefaults: 'readonly',
    useAttrs: 'readonly',
    useSlots: 'readonly',
    useTemplateRef: 'readonly',
    definePageMeta: 'readonly',
    defineNuxtConfig: 'readonly',
    defineNuxtPlugin: 'readonly',
    defineNuxtRouteMiddleware: 'readonly',
    defineEventHandler: 'readonly',
    useState: 'readonly',
    useFetch: 'readonly',
    useAsyncData: 'readonly',
    useRoute: 'readonly',
    useRouter: 'readonly',
    useRuntimeConfig: 'readonly',
    useHead: 'readonly',
    useSeoMeta: 'readonly',
    useCookie: 'readonly',
    navigateTo: 'readonly',
    createError: 'readonly',
    useNuxtApp: 'readonly',
    useLazyFetch: 'readonly',
    useLazyAsyncData: 'readonly',
    useRequestHeaders: 'readonly',
    useRequestURL: 'readonly',
    useError: 'readonly',
    clearError: 'readonly',
    refreshNuxtData: 'readonly',
    defineNuxtComponent: 'readonly',
    NuxtLink: 'readonly',
    NuxtPage: 'readonly',
    NuxtLayout: 'readonly',
    NuxtLoadingIndicator: 'readonly',
    NuxtErrorBoundary: 'readonly',
    NuxtImg: 'readonly',
    NuxtPicture: 'readonly',
    NuxtRouteAnnouncer: 'readonly',
    NuxtWelcome: 'readonly',
    ClientOnly: 'readonly',
    DevOnly: 'readonly',
    ServerPlaceholder: 'readonly',
    Icon: 'readonly',
    ref: 'readonly',
    computed: 'readonly',
    reactive: 'readonly',
    watch: 'readonly',
    watchEffect: 'readonly',
    onMounted: 'readonly',
    onUnmounted: 'readonly',
    nextTick: 'readonly',
    $fetch: 'readonly',
  },
  rules: {
    'accessor-pairs': [
      'error',
      {
        enforceForClassMembers: true,
        setWithoutGet: true,
      },
    ],
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'constructor-super': 'error',
    'default-case-last': 'error',
    'eqeqeq': ['error', 'smart'],
    'new-cap': [
      'error',
      {
        capIsNew: false,
        newIsCap: true,
        properties: true,
      },
    ],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-console': [
      'error',
      {
        allow: ['warn', 'error'],
      },
    ],
    'no-const-assign': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': [
      'error',
      {
        allowEmptyCatch: true,
      },
    ],
    'no-empty-character-class': 'off',
    'no-empty-pattern': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implied-eval': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'off',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-labels': [
      'error',
      {
        allowLoop: false,
        allowSwitch: false,
      },
    ],
    'no-lone-blocks': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': [
      'error',
      {
        builtinGlobals: false,
      },
    ],
    'no-regex-spaces': 'error',
    'no-restricted-globals': [
      'error',
      {
        message: 'Use `globalThis` instead.',
        name: 'global',
      },
      {
        message: 'Use `globalThis` instead.',
        name: 'self',
      },
    ],
    'no-restricted-properties': [
      'error',
      {
        message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.',
        property: '__proto__',
      },
      {
        message: 'Use `Object.defineProperty` instead.',
        property: '__defineGetter__',
      },
      {
        message: 'Use `Object.defineProperty` instead.',
        property: '__defineSetter__',
      },
      {
        message: 'Use `Object.getOwnPropertyDescriptor` instead.',
        property: '__lookupGetter__',
      },
      {
        message: 'Use `Object.getOwnPropertyDescriptor` instead.',
        property: '__lookupSetter__',
      },
    ],
    'no-self-assign': [
      'error',
      {
        props: true,
      },
    ],
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: false,
      },
    ],
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    'no-unused-vars': [
      'error',
      {
        // Antfu normally delegates this policy to eslint-plugin-unused-imports.
        // Oxlint's core rule covers the same diagnostics, without its fixer.
        args: 'after-used',
        argsIgnorePattern: '^_',
        ignoreRestSiblings: true,
        vars: 'all',
        varsIgnorePattern: '^_',
      },
    ],
    'no-use-before-define': [
      'error',
      {
        classes: false,
        functions: false,
        variables: true,
      },
    ],
    'no-useless-backreference': 'off',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-with': 'error',
    'object-shorthand': [
      'error',
      'always',
      {
        avoidQuotes: true,
        ignoreConstructors: false,
      },
    ],
    'one-var': [
      'error',
      {
        initialized: 'never',
      },
    ],
    'prefer-arrow-callback': [
      'error',
      {
        allowNamedFunctions: false,
        allowUnboundThis: true,
      },
    ],
    'prefer-const': [
      'error',
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-exponentiation-operator': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'symbol-description': 'error',
    'unicode-bom': ['error', 'never'],
    'use-isnan': [
      'error',
      {
        enforceForIndexOf: true,
        enforceForSwitchCase: true,
      },
    ],
    'valid-typeof': [
      'error',
      {
        requireStringLiterals: true,
      },
    ],
    'vars-on-top': 'error',
    'yoda': ['error', 'never'],
    'node/handle-callback-err': ['error', '^(err|error)$'],
    'node/no-exports-assign': 'error',
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    'jsdoc/check-access': 'warn',
    'jsdoc/check-property-names': 'warn',
    'jsdoc/empty-tags': 'warn',
    'jsdoc/implements-on-classes': 'warn',
    'jsdoc/no-defaults': 'warn',
    'jsdoc/require-param-name': 'warn',
    'jsdoc/require-property': 'warn',
    'jsdoc/require-property-description': 'warn',
    'jsdoc/require-property-name': 'warn',
    'jsdoc/require-returns-description': 'warn',
    // Oxlint names the same mode `prefer-top-level`.
    'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    'import/first': 'error',
    'import/no-duplicates': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-default': 'error',
    'import/newline-after-import': [
      'error',
      {
        count: 1,
      },
    ],
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/number-literal-case': 'error',
    'unicorn/prefer-dom-node-text-content': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-type-error': 'error',
    'unicorn/throw-new-error': 'error',
    'regexp/confusing-quantifier': 'warn',
    'regexp/control-character-escape': 'error',
    'regexp/match-any': 'error',
    'regexp/negation': 'error',
    'regexp/no-contradiction-with-assertion': 'error',
    'regexp/no-dupe-characters-character-class': 'error',
    'regexp/no-dupe-disjunctions': 'error',
    'regexp/no-empty-alternative': 'warn',
    'regexp/no-empty-capturing-group': 'error',
    'regexp/no-empty-character-class': 'error',
    'regexp/no-empty-group': 'error',
    'regexp/no-empty-lookarounds-assertion': 'error',
    'regexp/no-empty-string-literal': 'error',
    'regexp/no-escape-backspace': 'error',
    'regexp/no-extra-lookaround-assertions': 'error',
    'regexp/no-invalid-regexp': 'error',
    'regexp/no-invisible-character': 'error',
    'regexp/no-lazy-ends': 'warn',
    'regexp/no-legacy-features': 'error',
    'regexp/no-misleading-capturing-group': 'error',
    'regexp/no-misleading-unicode-character': 'error',
    'regexp/no-missing-g-flag': 'error',
    'regexp/no-non-standard-flag': 'error',
    'regexp/no-obscure-range': 'error',
    'regexp/no-optional-assertion': 'error',
    'regexp/no-potentially-useless-backreference': 'warn',
    'regexp/no-super-linear-backtracking': 'error',
    'regexp/no-trivially-nested-assertion': 'error',
    'regexp/no-trivially-nested-quantifier': 'error',
    'regexp/no-unused-capturing-group': 'error',
    'regexp/no-useless-assertions': 'error',
    'regexp/no-useless-backreference': 'error',
    'regexp/no-useless-character-class': 'error',
    'regexp/no-useless-dollar-replacements': 'error',
    'regexp/no-useless-escape': 'error',
    'regexp/no-useless-flag': 'warn',
    'regexp/no-useless-lazy': 'error',
    'regexp/no-useless-non-capturing-group': 'error',
    'regexp/no-useless-quantifier': 'error',
    'regexp/no-useless-range': 'error',
    'regexp/no-useless-set-operand': 'error',
    'regexp/no-useless-string-literal': 'error',
    'regexp/no-useless-two-nums-quantifier': 'error',
    'regexp/no-zero-quantifier': 'error',
    'regexp/optimal-lookaround-quantifier': 'warn',
    'regexp/optimal-quantifier-concatenation': 'error',
    'regexp/prefer-character-class': 'error',
    'regexp/prefer-d': 'error',
    'regexp/prefer-plus-quantifier': 'error',
    'regexp/prefer-predefined-assertion': 'error',
    'regexp/prefer-question-quantifier': 'error',
    'regexp/prefer-range': 'error',
    'regexp/prefer-set-operation': 'error',
    'regexp/prefer-star-quantifier': 'error',
    'regexp/prefer-unicode-codepoint-escapes': 'error',
    'regexp/prefer-w': 'error',
    'regexp/simplify-set-operations': 'error',
    'regexp/sort-flags': 'error',
    'regexp/strict': 'error',
    'regexp/use-ignore-case': 'error',
    'vue/no-arrow-functions-in-watch': 'error',
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-computed-properties-in-data': 'error',
    'vue/no-deprecated-data-object-declaration': 'error',
    'vue/no-deprecated-delete-set': 'error',
    'vue/no-deprecated-destroyed-lifecycle': 'error',
    'vue/no-deprecated-events-api': 'error',
    'vue/no-deprecated-model-definition': 'error',
    'vue/no-deprecated-props-default-this': 'error',
    'vue/no-deprecated-vue-config-keycodes': 'error',
    'vue/no-dupe-keys': 'off',
    'vue/no-export-in-script-setup': 'error',
    'vue/no-expose-after-await': 'error',
    'vue/no-lifecycle-after-await': 'error',
    'vue/no-reserved-component-names': 'error',
    'vue/no-reserved-keys': 'error',
    'vue/no-reserved-props': 'error',
    'vue/no-shared-component-data': 'error',
    'vue/no-side-effects-in-computed-properties': 'error',
    'vue/no-watch-after-await': 'error',
    'vue/prefer-import-from-vue': 'error',
    'vue/require-prop-type-constructor': 'error',
    'vue/require-render-return': 'error',
    'vue/require-slots-as-functions': 'error',
    'vue/return-in-computed-property': 'error',
    'vue/return-in-emits-validator': 'error',
    'vue/valid-define-emits': 'error',
    'vue/valid-define-options': 'error',
    'vue/valid-define-props': 'error',
    'vue/valid-next-tick': 'error',
    'vue/component-definition-name-casing': 'warn',
    'vue/prop-name-casing': ['error', 'camelCase'],
    'vue/require-default-prop': 'off',
    'vue/require-prop-types': 'off',
    'vue/no-multiple-slot-args': 'warn',
    'vue/no-required-prop-with-default': 'warn',
    'typescript/explicit-function-return-type': 'off',
  },
  overrides: [
    {
      files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
      rules: {
        // Antfu disables core rules here in favour of @typescript-eslint
        // equivalents. Oxlint's core rules already understand TypeScript, so
        // keep the root rules active and add only compatible TS-specific ones.
        'typescript/ban-ts-comment': [
          'error',
          {
            'ts-expect-error': 'allow-with-description',
          },
        ],
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-dynamic-delete': 'off',
        'typescript/no-empty-object-type': [
          'error',
          {
            allowInterfaces: 'always',
          },
        ],
        'typescript/no-explicit-any': 'off',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-extraneous-class': 'off',
        'typescript/no-invalid-void-type': 'off',
        'typescript/no-misused-new': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-nullish-coalescing': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-non-null-assertion': 'off',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-literal-enum-member': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/triple-slash-reference': 'off',
        'typescript/unified-signatures': 'off',
        'typescript/consistent-type-definitions': ['error', 'interface'],
        'typescript/consistent-type-imports': [
          'error',
          {
            disallowTypeAnnotations: false,
            fixStyle: 'separate-type-imports',
            prefer: 'type-imports',
          },
        ],
        'typescript/method-signature-style': ['error', 'property'],
        'typescript/no-import-type-side-effects': 'error',
      },
    },
    {
      files: [
        '**/__tests__/**/*.{js,jsx,ts,tsx,mjs,mts,cjs,cts}',
        '**/*.{spec,test,bench,benchmark}.{js,jsx,ts,tsx,mjs,mts,cjs,cts}',
      ],
      rules: {
        'vitest/consistent-test-it': [
          'error',
          {
            fn: 'it',
            withinDescribe: 'it',
          },
        ],
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/prefer-hooks-in-order': 'error',
        'vitest/prefer-lowercase-title': 'error',
        'no-unused-expressions': 'off',
        'typescript/explicit-function-return-type': 'off',
      },
    },
    {
      files: ['**/scripts/**/*.?([cm])[jt]s?(x)'],
      rules: {
        'no-console': 'off',
        'typescript/explicit-function-return-type': 'off',
      },
    },
    {
      files: ['**/cli/**/*.?([cm])[jt]s?(x)', '**/cli.?([cm])[jt]s?(x)'],
      rules: {
        'no-console': 'off',
      },
    },
    {
      files: ['**/*.js', '**/*.cjs'],
      rules: {
        'typescript/no-require-imports': 'off',
      },
    },
    {
      files: ['**/*.config.?([cm])[jt]s?(x)', '**/*.config.*.?([cm])[jt]s?(x)'],
      rules: {
        'no-console': 'off',
        'typescript/explicit-function-return-type': 'off',
      },
    },
  ],
  settings: {
    vue: {
      rules: {
        'vue/valid-v-html': 'error',
        'vue/valid-v-text': 'error',
        'vue/valid-v-show': 'error',
        'vue/valid-v-once': 'error',
        'vue/valid-v-cloak': 'error',
        'vue/require-v-for-key': 'error',
        'vue/valid-v-for': 'error',
        'vue/valid-v-model': 'error',
        'vue/no-v-for-template-key-on-child': 'error',
        'vue/no-use-v-if-with-v-for': 'error',
        'vue/no-template-key': 'error',
        'vue/no-duplicate-attributes': 'error',
        'vue/require-component-is': 'error',
        'vue/no-v-text-v-html-on-component': 'error',
        'vue/no-target-blank': 'off',
        'vue/this-in-template': 'warn',
        'vue/no-dupe-v-else-if': 'error',
        'vue/no-mutating-props': 'error',
        'vue/no-textarea-mustache': 'error',
        'vue/no-child-content': 'error',
        'vue/no-v-html': 'off',
        'vue/no-useless-mustaches': 'off',
        'vue/no-useless-v-bind': 'error',
        'vue/require-v-for-with-index-key': 'off',
        'vue/no-static-inline-styles': 'off',
      },
    },
  },
  ignorePatterns: [
    '**/node_modules/**',
    '**/dist/**',
    '**/.nuxt/**',
    '**/.output/**',
    '**/coverage/**',
  ],
  jsPlugins: ['eslint-plugin-regexp'],
}

export const fmtConfig = {
  singleQuote: true,
  jsxSingleQuote: false,
  semi: false,
  tabWidth: 2,
  useTabs: false,
  printWidth: 100,
  endOfLine: 'lf',
  insertFinalNewline: true,
  quoteProps: 'consistent',
  trailingComma: 'all',
  arrowParens: 'avoid',
  bracketSpacing: true,
  bracketSameLine: false,
  singleAttributePerLine: false,
  vueIndentScriptAndStyle: false,
  embeddedLanguageFormatting: 'auto',
  htmlWhitespaceSensitivity: 'css',
  objectWrap: 'preserve',
  proseWrap: 'preserve',
  sortImports: {
    groups: [
      'type-import',
      ['type-parent', 'type-sibling', 'type-index', 'type-internal'],
      'value-builtin',
      'value-external',
      'value-internal',
      ['value-parent', 'value-sibling', 'value-index'],
      'side_effect',
      'unknown',
    ],
    order: 'asc',
    ignoreCase: true,
    newlinesBetween: false,
  },
  sortPackageJson: true,
  ignorePatterns: [
    '**/node_modules/**',
    '**/dist/**',
    '**/.nuxt/**',
    '**/.output/**',
    '**/coverage/**',
  ],
}
